[project]
name = "contentprocessorapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "azure-appconfiguration>=1.7.1",
    "azure-identity>=1.20.0",
    "azure-storage-blob>=12.24.1",
    "azure-storage-queue>=12.12.0",
    "certifi>=2026.1.4",
    "fastapi[standard]>=0.128.0",
    "poppler-utils>=0.1.0",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.12.0",
    "pygments>=2.19.2",
    "pymongo>=4.15.5",
    "python-dotenv>=1.2.1",
    "starlette>=0.50.0",
    "uvicorn[standard]>=0.40.0",
    "h11==0.16.0",
    "urllib3==2.6.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "pytest-mock>=3.14.0",
    "coverage>=7.6.10",
    "pre-commit>=4.1.0",
    "ruff>=0.9.3",
]
